name: glimesh_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.1+67

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  janus_streaming_client:
    path: janus_streaming_client
  # Library is currently not built correctly for iOS, have to maintain our own local copy.
  #    git:
  #      url: https://github.com/flutterjanus/flutter_janus_client.git
  #      ref: c04b3e79fb8f6f39ea6bb68fd85176b9928a72f4
  # janus_client: ^2.1.1-beta
  graphql_flutter: ^5.0.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  phoenix_wings: ^1.0.2
  gql_phoenix_link: ^0.1.0
  auto_size_text: ^3.0.0-nullsafety.0
  oauth2: ^2.0.0
  url_launcher: ^6.0.12
  flutter_web_auth: ^0.4.1
  shared_preferences: ^2.0.8
  sentry_flutter: ^6.5.1
  font_awesome_flutter: ^9.1.0
  flutter_markdown: ^0.6.8
  cached_network_image: ^3.1.0+1
  wakelock: ^0.6.1+1
  flutter_staggered_grid_view: ^0.6.1
  gettext_i18n: ^1.0.4
  flutter_localizations: 
    sdk: flutter
    version: ^0.0.0
  plausible_analytics: ^0.1.3

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter_webrtc:
  git:
    url: https://github.com/glimesh/flutter-webrtc.git
    ref: 1eb2a95e159c299c81dc6c6a212d0fa789be7c55

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo-with-text-sm.png
    - assets/images/logo-with-text.png
    - assets/images/glimrip.png
    - assets/i18n/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
