// opted to do this instead of pulling in a whole dep to do this, esp. since we only
// use a few langs and they're readily available on the main repo.
const Map<String, String> languages = {
  "en": "English",
  "es": "Español",
  "es_AR": "Español rioplatense",
  "es_MX": "Español mexicano",
  "de": "Deutsch",
  "ja": "日本語",
  "nb": "Norsk Bokmål",
  "nn": "Norsk Nynorsk",
  "fr": "Français",
  "sv": "Svenska",
  "vi": "Tiếng Việt",
  "ru": "Русский",
  "ko": "한국어",
  "it": "Italiano",
  "bg": "български",
  "nl": "Nederlands",
  "fi": "Suomi",
  "pl": "Polski",
  "ro": "Limba Română",
  "pt_br": "Português Brasileiro",
  "pt": "Português",
  "zh_Hans": "中文 (简体)",
  "zh_Hant": "中文 (繁体)",
  "ar_eg": "العامية المصرية",
  "cs": "čeština",
  "da": "Dansk",
  "hu": "Magyar Nyelv",
  "ga": "Gaeilge",
  "sl": "slovenščina",
  "tr": "Türkçe",
};
